import { Eye, EyeOff, LockKeyhole, UnlockKeyhole, Layers, Info, PanelRightClose, ChevronDown } from 'lucide-react';
import { layerGroups, type Availability, type LayerId, type LayerLocks, type LayerValues, type LayerVisibility } from './cadLayers';

type Props = { visibility: LayerVisibility; opacities: LayerValues; locks: LayerLocks; availability: Availability; active: LayerId; imported: boolean; onActive: (id: LayerId) => void; onToggle: (id: LayerId) => void; onOpacity: (id: LayerId, value: number) => void; onLock: (id: LayerId) => void; onClose: () => void };
export default function LayersPanel(props: Props) {
  return <div className="cad-layers-panel"><div className="layers-panel-intro"><div><Layers size={15} /><b>Слои сцены</b><span>{Object.entries(props.visibility).filter(([id, visible]) => visible && props.availability[id as LayerId].available).length}</span></div><button title="Скрыть боковую панель" onClick={props.onClose}><PanelRightClose size={16} /></button></div>
    <div className="dataset-label"><span className="dataset-dot" /><div><b>{props.imported ? 'Поверхностный скан · STL / PLY' : 'Анатомическая демо-модель'}</b><small>{props.imported ? 'Сегментация не предоставлена' : 'Процедурная анатомия · не данные пациента'}</small></div><span>3D</span></div>
    {layerGroups.map(group => <section className="layer-group" key={group.title}><h3><ChevronDown size={11} />{group.title}<span>{group.layers.length}</span></h3>{group.layers.map(layer => {
      const available = props.availability[layer.id].available;
      const visible = available && props.visibility[layer.id];
      return <div className={`cad-layer-row ${visible ? 'is-visible' : 'is-hidden'} ${!available ? 'is-unavailable' : ''} ${props.active === layer.id ? 'is-active' : ''}`} key={layer.id} title={!available ? props.availability[layer.id].reason : undefined}>
        <div className="cad-layer-heading"><button className="layer-visibility" disabled={!available} title={visible ? 'Скрыть слой' : 'Показать слой'} aria-label={`${visible ? 'Скрыть' : 'Показать'}: ${layer.label}`} aria-pressed={visible} onClick={() => props.onToggle(layer.id)}>{visible ? <Eye size={14} /> : <EyeOff size={14} />}</button><span className={`layer-swatch swatch-${layer.swatch}`} /><button className="layer-name" disabled={!available} onClick={() => props.onActive(layer.id)}>{props.imported && layer.id === 'original' ? 'Исходная поверхность' : layer.id === 'roots' && !props.imported ? 'Корни · ДЕМО' : layer.label}</button><button className={`layer-lock ${props.locks[layer.id] ? 'locked' : ''}`} disabled={!available} title={props.locks[layer.id] ? 'Разрешить выбор слоя' : 'Запретить выбор и редактирование слоя'} aria-label={`Блокировка: ${layer.label}`} aria-pressed={props.locks[layer.id]} onClick={() => props.onLock(layer.id)}>{props.locks[layer.id] ? <LockKeyhole size={12} /> : <UnlockKeyhole size={12} />}</button></div>
        <label className="cad-layer-opacity"><span>Непрозрачность</span><input type="range" aria-label={`Непрозрачность: ${layer.label}`} min="0" max="100" value={props.opacities[layer.id]} disabled={!visible || !available} onChange={event => props.onOpacity(layer.id, Number(event.target.value))} /><small>{props.opacities[layer.id]}%</small></label>{layer.id === 'roots' && available && <div className="layer-unavailable-note">ДЕМО · не данные пациента. Десна при включении становится полупрозрачной.</div>}{!available && <div className="layer-unavailable-note">{['bone', 'pulp', 'nerves'].includes(layer.id) ? 'Нет данных слоя · нужна сегментация' : layer.id === 'target' ? 'Модель не загружена' : layer.id === 'preparation' ? 'Расчёт не выполнен' : props.availability[layer.id].reason}</div>}
      </div>;
    })}</section>)}
    <div className="layer-data-note"><Info size={14} /><p>Внутренние структуры не реконструируются из STL. Слой каналов управляет их подсветкой, а не геометрией Guide.{props.imported && ' Посадка процедурного Guide на импортированный скан не рассчитана.'}</p></div>
  </div>;
}
